blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path('<int:page>/', views.blog, name='blog'),
    path('pagination/<int:page>/', views.blog_pagination, name='pagination'),
    path('<slug:slug>/', views.single_blog, name='single_blog'),
    
]

shivamkumraa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.views.generic.base import TemplateView

from simple.sitemaps import BlogSitemap, StaticSitemap, BlogListSitemap

sitemaps = {
    'blog_list': BlogListSitemap,
    'blog': BlogSitemap,
    'static': StaticSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('simple.urls')),
    path('blog/', include('blog.urls')),

    # Seo Stuff
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    path("robots.txt",TemplateView.as_view(
        template_name="simple/robots.txt", content_type="text/plain")
    ),  #add the robots.txt file

]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simple/urls.py
from blog import views
from django.views.generic import TemplateView
from django.urls import path

TV = TemplateView.as_view

app_name="simple"

urlpatterns = [
    path('',  TV(template_name="simple/index.html"), name='index'),
    path('contact/',  TV(template_name="simple/contact.html"), name='contact'),
    path('terms/',  TV(template_name="simple/terms.html"), name='terms'),
    path('privacy/',  TV(template_name="simple/privacy.html"), name='privacy'),

]

blog/models.py
from django.db import models

class Blog(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=255, unique=True)
    content = models.TextField()
    meta_description = models.CharField(max_length=255)

    def get_short_description(self):
        return self.content[:192]
    
    def get_json(self):
        return {
            "title": self.title,
            "slug": self.slug,
            "meta_description": self.meta_description
        }

    def __str__(self):
        return self.title

class BlogImage(models.Model):
    image = models.ImageField(upload_to="blog_images/")

    def __str__(self):
        return self.image.url

simple/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Blog
from django.core.paginator import Paginator
from django.http import JsonResponse, HttpResponseNotFound
from django.conf import settings


def blog(request, page):
    blogs = Blog.objects.all().order_by("-pk")
    paginator = Paginator(blogs, settings.ARTICLE_PAGINATE_BY)  

    try:
        current_page = paginator.page(page)
    except:
        return HttpResponseNotFound('<h1>404 page Not Found</h1>')

    context = {
        "current": page,
        "current_page": current_page,
        "paginator": paginator,
    }
    return render(request, 'blog/blog.html', context)

def blog_pagination(request, page):
    blogs = Blog.objects.all().order_by("-pk")
    paginator = Paginator(blogs, settings.ARTICLE_PAGINATE_BY)

    try:
        page = paginator.page(page)
    except:
        return JsonResponse({'blogs':[],'has_next':None}, status=404)

    has_next = page.has_next()

    objects = [blog.get_json() for blog in page.object_list]
    context = {
        "blogs": objects,
        "has_next": has_next
    }

    return JsonResponse(context)


def single_blog(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    return render(request, 'blog/single.html', {'blog': blog})

simple/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/blog.html
{% extends 'simple/base.html' %}
{% load static %}

{% block title %}Blog | shivamkumraa.com{% endblock %}

{% block content %}
<section class="ftco-section all-blogs">
    <div class="container px-md-0">
        <h1 class="mb-5 text-center">All Tutorials</h1>
            <div class="blog-list">
                {% for blog in current_page.object_list %}
                    <div>
                        <div class="col-sm-12 col-md-10 col-lg-8 mx-auto p-sm-5 py-3 px-5 mb-4 blog">
                            <h4 class="mb-2">
                                <a href="{% url 'blog:single_blog' blog.slug %}">{{ blog.title }}</a>
                            </h4>
                            <p class="mt-4">{{ blog.meta_description }}... <a href="{% url 'blog:single_blog' blog.slug %}">Read More</a> </p>
                        </div>
                    </div>
                {% endfor %}
            </div>
    
            <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if current_page.has_previous is False %}disabled{% endif %}">
                          <a class="page-link" href="{% if current_page.has_previous %}{% url 'blog:blog' current_page.previous_page_number %}{% endif %}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                          </a>
                        </li>
                        
                        {% for number in paginator.page_range %}
                            <li class="page-item {% if current == number %}active{% endif %}"><a class="page-link" href="{% url 'blog:blog' number %}">{{ number }}</a></li>
                        {% endfor %}
                        <li class="page-item {% if current_page.has_next is False %}disabled{% endif %}">
                          <a class="page-link" href="{% if current_page.has_next %}{% url 'blog:blog' current_page.next_page_number %}{% endif %}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                          </a>
                        </li>
                      </ul>
              </nav>
              

            <!-- Infinite Loader -->
            {% if has_next %}
            <!-- <div class="text-center">
                <a id="loadmore" href="#" class="btn btn-primary py-3 px-5">Load More</a>
            </div> -->
            {% endif %}
    </div>

</section>
{% endblock %}

{% block javascript %}
<!-- Infinite Loader Javascript -->
<!-- <script>
    const LOADMORE = document.querySelector("#loadmore")
    const BLOGLIST = document.querySelector(".blog-list")
    if(LOADMORE){
        let PAGE = 2
        LOADMORE.addEventListener("click", (event)=>{
            LOADMORE.innerHTML = `
            <div class="spinner-border text-light" role="status">
                <span class="sr-only">Loading...</span>
            </div>
            `
            $.ajax(`/blog/pagination/${PAGE}/`,{
                success: function(data, status, xhr){

                    data.blogs.forEach(element => {
                        let div = document.createElement("div")
                        div.innerHTML = `
<div class="col-sm-12 col-md-10 col-lg-8 mx-auto p-sm-5 py-3 px-5 mb-4 blog">
    <h4 class="mb-2">
        <a href="/blog/${element.slug}/">${element.title}</a>
    </h4>
    <p class="mt-4">${element.meta_description}... <a href="/blog/${element.slug}/">Read More</a> </p>
</div>
                        `
                        BLOGLIST.appendChild(div)
                    });

                    PAGE++
                    if(!data.has_next){
                        LOADMORE.style.display = "none";
                    }
                    LOADMORE.innerHTML = 'Load More'
                }
            })
            
        })
    }
</script> -->
{% endblock %}

blog/templates/blog/single.html
{% extends 'simple/base.html' %}
{% load static %}

{% block title %}{{ blog.title }} | shivamkumraa.com{% endblock %}
{% block head %}
<meta name="description" content="{{ blog.meta_description }}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/styles/monokai-sublime.min.css" integrity="sha512-ade8vHOXH67Cm9z/U2vBpckPD1Enhdxl3N05ChXyFx5xikfqggrK4RrEele+VWY/iaZyfk7Bhk6CyZvlh7+5JQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />    
{% endblock %}
{% block content %}
<section class="ftco-section single-blog">
    <div class="container px-md-0">
            <div class="col-sm-12 col-md-10 col-lg-8 mx-auto">
                <h1 class="mb-5 mt-3 text-center">{{ blog.title }}</h1>
                {{ blog.content|safe }}
            </div>
    </div>
</section>

{% endblock %}

{% block javascript %}
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/highlight.min.js"></script>
<script>hljs.highlightAll();</script>

{% endblock %}

simple/templates/simple/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>

    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'simple/css/style.css' %}">

    {% block head %}
    {% endblock %}
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-201551124-1">
    </script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'UA-201551124-1');
    </script>
	<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" /> -->
  </head>
  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
	  
	  
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar ftco-navbar-light site-navbar-target scrolled awake" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="{% url 'simple:index' %}"><span>S</span>hivam</a>
	      <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <svg width="18px" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="bars" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" class="svg-inline--fa fa-bars fa-w-14 fa-2x"><path fill="currentColor" d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z" class=""></path></svg>
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav nav ml-auto">
	          <li class="nav-item"><a href="{% url 'simple:index' %}" class="nav-link"><span>Home</span></a></li>
	          <li class="nav-item"><a href="{% url 'simple:index' %}#about-section" class="nav-link"><span>About</span></a></li>
	          <!-- <li class="nav-item"><a href="#skills-section" class="nav-link"><span>Skills</span></a></li> -->
	          <li class="nav-item"><a href="{% url 'simple:index' %}#services-section" class="nav-link"><span>Services</span></a></li>
	          <li class="nav-item"><a href="{% url 'simple:index' %}#testimonial-section" class="nav-link"><span>Testimonials</span></a></li>
	          <!-- <li class="nav-item"><a href="{% url 'simple:index' %}#projects-section" class="nav-link"><span>Projects</span></a></li> -->
	          <li class="nav-item"><a href="{% url 'simple:index' %}#contact-section" class="nav-link {% if request.path == '/contact/' %}active{% endif %}"><span>Contact</span></a></li>
	          <li class="nav-item"><a href="{% url 'blog:blog' 1 %}" class="nav-link {% if request.path == '/blog/' %}active{% endif %}"><span>Blog</span></a></li>
            </ul>
	      </div>
	    </div>
	  </nav>
    
      {% block content %}
      {% endblock %}

    <footer class="ftco-footer ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">About</h2>
              <p>I am a professional full-stack developer with 3+ years of experience in the industry. My passion is writing code and building robust products and web applications.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li>
					<a href="https://github.com/shivamkumraa9/" target="_blank">
						<span>
							<svg width="25px" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="github" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512" class="svg-inline--fa fa-github fa-w-16 fa-2x"><path fill="currentColor" d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z" class=""></path></svg>
						</span>
					</a>
				</li>
                <li>
					<a href="https://www.linkedin.com/in/shivam-kumr/" target="_blank">
						<span>
							<svg width="25px" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="linkedin" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" class="svg-inline--fa fa-linkedin fa-w-14 fa-2x"><path fill="currentColor" d="M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.3c0-17.8-14.4-32.3-32-32.3zM135.4 416H69V202.2h66.5V416zm-33.2-243c-21.3 0-38.5-17.3-38.5-38.5S80.9 96 102.2 96c21.2 0 38.5 17.3 38.5 38.5 0 21.3-17.2 38.5-38.5 38.5zm282.1 243h-66.4V312c0-24.8-.5-56.7-34.5-56.7-34.6 0-39.9 27-39.9 54.9V416h-66.4V202.2h63.7v29.2h.9c8.9-16.8 30.6-34.5 62.9-34.5 67.2 0 79.7 44.3 79.7 101.9V416z" class=""></path></svg>
						</span>
					</a>
				</li>
			  </ul>

            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-4">
              <h2 class="ftco-heading-2">Links</h2>
              <ul class="list-unstyled">
                <li><a href="{% url 'simple:index' %}#home-section"><span class="icon-long-arrow-right mr-2"></span>Home</a></li>
                <li><a href="{% url 'blog:blog' 1 %}"><span class="icon-long-arrow-right mr-2"></span>Blog</a></li>
                <li><a href="{% url 'simple:index' %}#services-section"><span class="icon-long-arrow-right mr-2"></span>Services</a></li>
                <li><a href="{% url 'simple:index' %}#projects-section"><span class="icon-long-arrow-right mr-2"></span>Projects</a></li>
                <li><a href="{% url 'simple:index' %}#testimonial-section"><span class="icon-long-arrow-right mr-2"></span>Testimonials</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Pages</h2>
              <ul class="list-unstyled">
                <li><a href="{% url 'simple:privacy' %}"><span class="icon-long-arrow-right mr-2"></span>Privacy Policy</a></li>
                <li><a href="{% url 'simple:terms' %}"><span class="icon-long-arrow-right mr-2"></span>Terms</a></li>
                <li><a href="{% url 'simple:index' %}#about-section"><span class="icon-long-arrow-right mr-2"></span>About</a></li>
                <li><a href="/sitemap.xml"><span class="icon-long-arrow-right mr-2"></span>Site Map</a></li>
                <li><a href="{% url 'simple:contact' %}"><span class="icon-long-arrow-right mr-2"></span>Contact</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="mb-3">
	              <ul class="list-unstyled">
	                <li><span class="icon icon-map-marker"></span><span class="text">City: Ludhiana, Punjab, India</span></li>
	                <li><a href="#"><span></span><span class="text">+91 7901844892</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">shivamkumraa9@gmail.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p>
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | shivamkumraa.com
          </div>
        </div>
      </div>
    </footer>
	<script src="{% static 'simple/js/jquery.min.js' %}"></script>
	<script src="{% static 'simple/js/jquery.easing.1.3.js' %}"></script>
	<script src="{% static 'simple/js/popper.min.js' %}"></script>
	<script src="{% static 'simple/js/bootstrap.min.js' %}"></script>

    {% block javascript %}
    {% endblock %} 
  </body>
</html>